version: '3.8'
services:
  node:
    image: ghcr.io/gnosischain/gbc-lighthouse:v2.0.1-gbc
    command: |
      lighthouse beacon_node
      --testnet-dir /sbc_test/config
      --discovery-port 12000
      --port 13000
      --eth1-endpoints $XDAI_RPC_URL
      --enr-address $IP_NODE
      --enr-udp-port 12000
      --datadir /home/.eth2/beaconchaindata
      --http-address 0.0.0.0
      --http
      --debug-level debug
    network_mode: host
    volumes:
      - /root/sbc_test/config:/sbc_test/config
      - /root/sbc_test/node_db:/home/.eth2/beaconchaindata
      - /root/sbc_test/slasher_db:/home/.eth2/slasherdata
  validator-init:
    image: ghcr.io/gnosischain/gbc-lighthouse:v2.0.1-gbc
    command: |
      lighthouse account_manager validator import
      --testnet-dir /sbc_test/config
      --password-file /sbc_test/config/keystore_password.txt
      --reuse-password
      --directory /sbc_test/config/validator_keys
      --datadir /sbc_test
    volumes:
      - /root/sbc_test/config:/sbc_test/config
      - /root/sbc_test/validators:/sbc_test/validators
  validator:
    image: ghcr.io/gnosischain/gbc-lighthouse:v2.0.1-gbc
    command: |
      lighthouse validator_client
      --testnet-dir /sbc_test/config
      --validators-dir /sbc_test/validators
      --graffiti-file=/sbc_test/config/graffiti.yml
      --beacon-nodes http://localhost:5052
    volumes:
      - /root/sbc_test/config:/sbc_test/config
      - /root/sbc_test/validators:/sbc_test/validators
    network_mode: host
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }
