version: '3.8'
services:
  node1:
    image: prysmaticlabs/prysm-beacon-chain:v1.4.2
    command: |
      --accept-terms-of-use
      --contract-deployment-block 9063718
      --http-web3provider https://rinkeby.infura.io/v3/8e6efb6da18f4861b45aa22494b129c9
      --bootstrap-node ""
      --config-file /config
      --chain-config-file /config
      --rpc-host 0.0.0.0
      --p2p-priv-key /nodekey1
      --p2p-local-ip 0.0.0.0
      --p2p-host-ip 192.168.144.2
      --disable-sync
    volumes:
      - ./config.yml:/config
      - ./nodekey1.txt:/nodekey1
      - ./node1:/home/.eth2/beaconchaindata
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }
    networks:
      sbc:
        ipv4_address: 192.168.144.2
  node2:
    image: prysmaticlabs/prysm-beacon-chain:v1.4.2
    command: |
      --accept-terms-of-use
      --contract-deployment-block 9063718
      --http-web3provider https://rinkeby.infura.io/v3/8e6efb6da18f4861b45aa22494b129c9
      --bootstrap-node ""
      --config-file /config
      --chain-config-file /config
      --rpc-host 0.0.0.0
      --p2p-priv-key /nodekey2
      --p2p-local-ip 0.0.0.0
      --p2p-host-ip 192.168.144.3
      --disable-sync
      --peer "enr:-LK4QDnGYXm6pg_rwprfgSCFX4QlU_hkxqpg2ohUaaqYxEyKX-GaZLMy2yzECYOwF_C_aYL6DwMJR9SVJneZPWjRtgUBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAJqmwXAABkZP__________gmlkgnY0gmlwhMCokAKJc2VjcDI1NmsxoQP6LetjuULxgOB7ztO0qMaXqWBaCO4foFk7roPPLrZcHIN0Y3CCMsiDdWRwgi7g"
    volumes:
      - ./config.yml:/config
      - ./nodekey2.txt:/nodekey2
      - ./node2:/home/.eth2/beaconchaindata
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }
    networks:
      sbc:
        ipv4_address: 192.168.144.3
  validator-init:
    image: prysmaticlabs/prysm-validator:v1.3.11
    command: |
      wallet recover
      --mnemonic-file /mnemonic
      --accept-terms-of-use
      --wallet-password-file /password
      --skip-mnemonic-25th-word-check true
      --num-accounts 4096
    volumes:
      - ./password.txt:/password
      - ./mnemonic.txt:/mnemonic
      - ./wallet:/home/.eth2validators/prysm-wallet-v2
    networks:
      sbc:
  validator-list:
    image: prysmaticlabs/prysm-validator:v1.3.11
    command: |
      accounts list
      --accept-terms-of-use
      --wallet-password-file /password
    volumes:
      - ./password.txt:/password
      - ./mnemonic.txt:/mnemonic
      - ./wallet:/home/.eth2validators/prysm-wallet-v2
    networks:
      sbc:
  validator:
    image: prysmaticlabs/prysm-validator:v1.3.11
    command: |
      --accept-terms-of-use
      --config-file /config
      --chain-config-file /config
      --wallet-password-file /password
      --beacon-rpc-provider node1:4000
    volumes:
      - ./password.txt:/password
      - ./config.yml:/config
      - ./wallet:/home/.eth2validators/prysm-wallet-v2
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }
    networks:
      sbc:
  explorer:
    image: gobitfly/eth2-beaconchain-explorer:staging
    command: ./explorer --config /explorer_config
    volumes:
      - ./explorer/config.yml:/explorer_config
      - ./config.yml:/config
      - ./explorer/imprint.html:/imprint
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }
    ports:
      - '3333:3333'
    networks:
      sbc:
  postgres:
    image: postgres:13-alpine
    command: postgres -c fsync=off
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sbc_test_db
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./explorer/tables.sql:/docker-entrypoint-initdb.d/tables.sql
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }
    networks:
      sbc:
networks:
  sbc:
    external: true
# docker network create sbc --subnet 192.168.144.0/24
