version: '3.8'
services:
  node:
    image: kirillfedoseev/lighthouse
    command: |
      lighthouse beacon_node
      --testnet-dir /sbc_test/config
      --discovery-port 12000
      --enr-udp-port 12000
      --port 13000
      --eth1-endpoints https://rinkeby.infura.io/v3/$INFURA_ID
      --disable-enr-auto-update
      --datadir /home/.eth2/beaconchaindata
      --boot-nodes $BOOTNODE
      --enr-address $IP_NODE
      --http-address 0.0.0.0
      --http
      --debug-level debug
    ports:
      - '12000:12000/udp'
      - '13000:13000'
      - '5052:5052'
    volumes:
      - /root/sbc_test/config:/sbc_test/config
      - /root/sbc_test/node_db:/home/.eth2/beaconchaindata
  validator-init:
    image: kirillfedoseev/lighthouse
    command: |
      lighthouse account_manager validator import
      --testnet-dir /sbc_test/config
      --password-file /sbc_test/config/keystore_password.txt
      --reuse-password
      --directory /sbc_test/config/validator_keys
      --datadir /sbc_test
    volumes:
      - /root/sbc_test/config:/sbc_test/config
      - /root/sbc_test/validators:/sbc_test/validators
  validator:
    image: kirillfedoseev/lighthouse
    command: |
      lighthouse validator_client
      --testnet-dir /sbc_test/config
      --validators-dir /sbc_test/validators
      --beacon-nodes http://node:5052
    volumes:
      - /root/sbc_test/config:/sbc_test/config
      - /root/sbc_test/validators:/sbc_test/validators
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }
