version: '3.8'
services:
  node:
    image: ghcr.io/openethereum/sbc-prysm-beacon-chain:v2.0.2-sbc
    command: |
      --accept-terms-of-use
      --contract-deployment-block 22694907
      --http-web3provider $XDAI_RPC_URL
      --bootstrap-node /sbc_test/config/boot_enr.yaml
      --config-file /sbc_test/config/config.yaml
      --chain-config-file /sbc_test/config/config.yaml
      --rpc-host 0.0.0.0
      --p2p-local-ip 0.0.0.0
      --p2p-host-ip $IP_NODE
      --subscribe-all-subnets
      --historical-slasher-node
      --grpc-gateway-host 0.0.0.0
      --monitoring-host 0.0.0.0
      --verbosity debug
      --enable-debug-rpc-endpoints
    ports:
      - '12000:12000/udp'
      - '13000:13000'
      - '4000:4000'
      - '3500:3500'
      - '8080:8080'
    volumes:
      - /root/sbc_test/config:/sbc_test/config
      - /root/sbc_test/node_db:/home/.eth2/beaconchaindata
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }
  validator-init:
    image: ghcr.io/openethereum/sbc-prysm-validator:v2.0.2-sbc
    command: |
      wallet recover
      --accept-terms-of-use
      --mnemonic-file /sbc_test/config/mnemonic.txt
      --wallet-password-file /sbc_test/config/wallet_password.txt
      --skip-mnemonic-25th-word-check true
      --num-accounts 1024
    volumes:
      - /root/sbc_test/config:/sbc_test/config
      - /root/sbc_test/wallet:/home/.eth2validators/prysm-wallet-v2
  validator-import:
    image: ghcr.io/openethereum/sbc-prysm-validator:v2.0.2-sbc
    command: |
      accounts import
      --accept-terms-of-use
      --keys-dir /sbc_test/config/validator_keys
      --account-password-file /sbc_test/config/keystore_password.txt
      --wallet-password-file /sbc_test/config/wallet_password.txt
    volumes:
      - /root/sbc_test/config:/sbc_test/config
      - /root/sbc_test/wallet:/home/.eth2validators/prysm-wallet-v2
  validator-list:
    image: ghcr.io/openethereum/sbc-prysm-validator:v2.0.2-sbc
    command: |
      accounts list
      --accept-terms-of-use
      --wallet-password-file /sbc_test/config/wallet_password.txt
    volumes:
      - /root/sbc_test/config:/sbc_test/config
      - /root/sbc_test/wallet:/home/.eth2validators/prysm-wallet-v2
  validator-exit:
    image: ghcr.io/openethereum/sbc-prysm-validator:v2.0.2-sbc
    command: |
      accounts voluntary-exit
      --public-keys $PUBKEY
      --accept-terms-of-use
      --wallet-password-file /sbc_test/config/wallet_password.txt
      --beacon-rpc-provider node:4000
    stdin_open: true
    tty: true
    volumes:
      - /root/sbc_test/config:/sbc_test/config
      - /root/sbc_test/wallet:/home/.eth2validators/prysm-wallet-v2
  validator:
    image: ghcr.io/openethereum/sbc-prysm-validator:v2.0.2-sbc
    command: |
      --accept-terms-of-use
      --config-file /sbc_test/config/config.yaml
      --chain-config-file /sbc_test/config/config.yaml
      --wallet-password-file /sbc_test/config/wallet_password.txt
      --beacon-rpc-provider node:4000
    volumes:
      - /root/sbc_test/config:/sbc_test/config
      - /root/sbc_test/wallet:/home/.eth2validators/prysm-wallet-v2

